beginning of deck builder aspect
Assets\01_kinship_actual\scripts\Combat_Scripts\Player_Combat.cs(41,13): error CS0103: The name 'newDeck' does not exist in the current context